name: info

on:
  pull_request:
    branches:
      - main
    paths:
      - "bin/**/*.rs"
      - "**/Cargo.toml"
      - "crates/**/*.rs"
      - ".github/workflows/binary-size.yml"

# Cancel in progress workflow when a new one is triggered by running in a concurrency group
# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobs
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  binary-size-base:
    name: Base Branch Binary Size
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    container:
      image: ghcr.io/dojoengine/katana-dev:latest
    outputs:
      size: ${{ steps.binary-size.outputs.size }}
      branch: ${{ steps.binary-size.outputs.branch }}

    steps:
      - uses: actions/checkout@v4
      # Workaround for https://github.com/actions/runner-images/issues/6775
      - run: git config --global --add safe.directory "*"

      - uses: Swatinem/rust-cache@v2
        with:
          key: binary-size-base

      - name: Get binary size (base)
        id: binary-size
        run: |
          git fetch origin ${{ github.base_ref }}
          git checkout origin/${{ github.base_ref }}
          cargo build --release --bin katana
          BINARY_SIZE=$(stat --format %s ./target/release/katana)
          echo "size=$BINARY_SIZE" >> $GITHUB_OUTPUT
          echo "branch=${{ github.base_ref }}" >> $GITHUB_OUTPUT

  binary-size-pr:
    name: PR Branch Binary Size
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    container:
      image: ghcr.io/dojoengine/katana-dev:latest
    outputs:
      size: ${{ steps.binary-size.outputs.size }}
      branch: ${{ steps.binary-size.outputs.branch }}

    steps:
      - uses: actions/checkout@v4
      # Workaround for https://github.com/actions/runner-images/issues/6775
      - run: git config --global --add safe.directory "*"

      - uses: Swatinem/rust-cache@v2
        with:
          key: binary-size-pr

      - name: Get binary size (PR)
        id: binary-size
        run: |
          git checkout ${{ github.sha }}
          cargo build --release --bin katana
          BINARY_SIZE=$(stat --format %s ./target/release/katana)
          echo "size=$BINARY_SIZE" >> $GITHUB_OUTPUT
          echo "branch=${{ github.head_ref }}" >> $GITHUB_OUTPUT

  generate-report:
    name: Generate Binary Size Report
    needs: [binary-size-base, binary-size-pr]
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    container:
      image: ghcr.io/dojoengine/katana-dev:latest

    steps:
      - uses: actions/checkout@v4
      - run: git config --global --add safe.directory "*"

      - name: Generate binary size report
        id: size-report
        shell: bash
        run: |
          REPORT=$(./scripts/generate-binary-size-report.sh ${{ needs.binary-size-base.outputs.branch }} ${{ needs.binary-size-base.outputs.size }} ${{ needs.binary-size-pr.outputs.branch }} ${{ needs.binary-size-pr.outputs.size }})
          echo "report<<EOF" >> $GITHUB_OUTPUT
          echo "$REPORT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Find existing comment
        uses: peter-evans/find-comment@v2
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: Binary size report

      - name: Comment binary size
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            try {
              const body = `${{ steps.size-report.outputs.report }}`;
              const commentId = '${{ steps.find-comment.outputs.comment-id }}';

              if (commentId && commentId.trim() !== '') {
                await github.rest.issues.updateComment({
                  comment_id: parseInt(commentId),
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: body
                });
                console.log('Updated existing comment with binary size report');
              } else {
                await github.rest.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: body
                });
                console.log('Created new comment with binary size report');
              }
            } catch (error) {
              console.error('Error posting binary size comment:', error);
              core.setFailed(`Failed to post binary size comment: ${error.message}`);
            }
